[package]
name = "rustgl"
version = "0.1.0"
edition = "2021"

[dependencies]
beryllium = "0.13.3"
imagine = "0.0.5"
bytemuck = "1"
ogl33 = { version = "0.2.0", features = ["debug_error_checks"]}

[dev-dependencies]